# AUTO-GENERATED — do not edit. Run `node scripts/codegen-schemas.mjs` to regenerate.
# Source: schemas/analytics-events.json (46 events)
from __future__ import annotations
from typing import Literal

ApprovedEvent = Literal[
    "user_signed_up",
    "user_signed_in",
    "user_signed_out",
    "user_password_reset_requested",
    "user_password_reset_completed",
    "user_email_verified",
    "trial_started",
    "trial_converted",
    "trial_expired",
    "subscription_created",
    "subscription_updated",
    "subscription_canceled",
    "payment_succeeded",
    "payment_failed",
    "checkout_started",
    "checkout_completed",
    "onboarding_started",
    "onboarding_step_completed",
    "onboarding_completed",
    "invite_sent",
    "invite_accepted",
    "file_uploaded",
    "file_downloaded",
    "export_generated",
    "lead_magnet_submitted",
    "lead_magnet_delivered",
    "page_viewed",
    "feature_flag_evaluated",
    "audit_record_created",
    "report_generated",
    "document_extracted",
    "extraction_job_started",
    "extraction_job_failed",
    "grant_application_created",
    "grant_application_submitted",
    "vpn_session_started",
    "vpn_session_ended",
    "property_inspection_created",
    "lease_parsed",
    "support_ticket_opened",
    "feedback_submitted",
    "error_boundary_triggered",
    "api_error_occurred",
    "workspace_created",
    "member_added",
    "member_removed",
]

APPROVED_EVENTS: tuple[ApprovedEvent, ...] = (
    "user_signed_up",
    "user_signed_in",
    "user_signed_out",
    "user_password_reset_requested",
    "user_password_reset_completed",
    "user_email_verified",
    "trial_started",
    "trial_converted",
    "trial_expired",
    "subscription_created",
    "subscription_updated",
    "subscription_canceled",
    "payment_succeeded",
    "payment_failed",
    "checkout_started",
    "checkout_completed",
    "onboarding_started",
    "onboarding_step_completed",
    "onboarding_completed",
    "invite_sent",
    "invite_accepted",
    "file_uploaded",
    "file_downloaded",
    "export_generated",
    "lead_magnet_submitted",
    "lead_magnet_delivered",
    "page_viewed",
    "feature_flag_evaluated",
    "audit_record_created",
    "report_generated",
    "document_extracted",
    "extraction_job_started",
    "extraction_job_failed",
    "grant_application_created",
    "grant_application_submitted",
    "vpn_session_started",
    "vpn_session_ended",
    "property_inspection_created",
    "lease_parsed",
    "support_ticket_opened",
    "feedback_submitted",
    "error_boundary_triggered",
    "api_error_occurred",
    "workspace_created",
    "member_added",
    "member_removed",
)

VentoraProduct = Literal["camaudit", "camaudit-v2", "grantpipe", "lextract", "floriva", "streamvpn"]
